### ISSUE TITLE
Error: Permission denied to access object

### ISSUE THREAD

**Issue by Santya95** [Sau1707/ModernBot#10]
Error: Permission denied to access object self-hosted:349:19

- find self-hosted:349
- AutoBuild user-script:raw.githubusercontent.com/ModernBot:395

**Comment by Sau1707** [comment]
How do you exactly are you trying to install it?

**Comment by Santya95** [comment]
from the website, I install the greasemonkey script

**Comment by Sau1707** [comment]
I'll take a look at that once I have time this week then

**Comment by Sau1707** [comment]
Nada, looks like greasemonkey has some difference from tampermoney.

If you are planning using the bot consider moving to a different browser, I suggest brave since support tampermoney and has a nice ad-block installed
