### ISSUE TITLE
Ref error, sorry if i'm stressing you out

### ISSUE THREAD

**Issue by Santya95** [Sau1707/ModernBot#4]
const key = `${id}_${Game.world_id}`;

1. ReferenceError: Game is not defined [sandbox eval code:41:24]

-     load user-script:raw.githubusercontent.com/ModernBot:41
-     AutoGratis user-script:raw.githubusercontent.com/ModernBot:981
-     ModernBot user-script:raw.githubusercontent.com/ModernBot:1635
-     userScript user-script:raw.githubusercontent.com/ModernBot:1701

Glad to be your first user :)

**Comment by Sau1707** [comment]
Okay this will take a bit longer, I'm gonna doit in the evening
