### ISSUE TITLE
Not working after last update

### ISSUE THREAD

**Issue by Seven2199** [Sau1707/ModernBot#42]
The configurations icon no longer show up after the last update, auto farming looks like it's running but the resources are actually not not being delivered

**Comment by Sau1707** [comment]
Can you provide a screenshot of the error? I currently don't have an account with multiple polis to test it out...

**Comment by FancyGoat22** [comment]
there's a typoo, I raised issue for it. You can fix it manually @Seven2199  until its patched anyway

**Comment by Sau1707** [comment]
Fidex

**Comment by Seven2199** [comment]
Hey,

Sorry for the delay.

Thanks for the update.

The farming issue appears to be resolved after this last patch, however,
the configurations window and icon still don't show up as it used to.

**Comment by Sau1707** [comment]
Can you provide the error that show up in the console? To me it works fine.

Right click -> inspect -> console
